// File included from various parts inside mpg123. By default, this file is generated by autoconfig.

// On Windows, we need the file from 'ports/' to get <stddef>.
#ifdef _MSC_VER
// 'config.h' will include the appropriate version of mpg123.h for us.
#include "config.h"
#else
#define MPG123_NO_CONFIGURE
#include "mpg123/src/libmpg123/mpg123.h.in"
#endif
