use test;
use sql;
use core:io;

DATABASE SimpleDB {
	TABLE test(
		id INTEGER PRIMARY KEY,
		name TEXT
	);
}

suite Simple {
	SQLite baseDb; // (cwdUrl / ".." / "test.db");
	SimpleDB c(baseDb);

	Str test = "variable";
	WITH c: INSERT INTO test VALUES (3, "test's");
	WITH c: INSERT INTO test(id, name) VALUES (4, test);

	WITH c: UPDATE test SET name = name || " " || test WHERE id == 2 + 1;

	// for (row in WITH c: SELECT * FROM test) {
	// 	print("${row.id} - ${row.name}");
	// }

	test 1 == 0;
}
