use test;
use sql;
use core:io;

DATABASE SimpleDB {
	TABLE test(
		id INTEGER PRIMARY KEY,
		name TEXT,
		city TEXT
	);
}

suite Simple {
	SQLite baseDb; // (cwdUrl / ".." / "test.db");
	SimpleDB c(baseDb);

	Str test = "variable";
	WITH c: INSERT INTO test VALUES (3, "test's", "city");
	WITH c: INSERT INTO test(id, name) VALUES (4, test);
	var insertedId = WITH c: INSERT INTO test(name) VALUES ("auto-id");
	print("Inserted id: ${insertedId}");

	WITH c: UPDATE test SET name = name || " " || test WHERE id == 2 + 1;

	var removed = WITH c: DELETE FROM test WHERE id == insertedId;
	print("Removed ${removed}");

	print("Contents of the table:");
	for (row in WITH c: SELECT * FROM test) {
		print("  ${row.id} - ${row.name}");
	}

	test 1 == 0;
}
