use io;


void test2() {

	/////////////////////////
	//Database from memory //
	/////////////////////////

    print("Opening connection to db:");
    SQLite db();

    Statement creation = db.prepare("CREATE TABLE IF NOT EXISTS Theboys(id INTEGER, name TEXT)");
    if(creation.execute)
		print("tjohjo");
    else
		print(creation.errMsg);

    creation.finalize;

    Statement insertion = db.prepare("INSERT INTO Theboys (id, name) VALUES (0, 'Markus')");
	if(insertion.execute)
		print("tjohjo2");
    else
		print(insertion.errMsg);

	insertion = db.prepare("INSERT INTO Theboys (id, name) VALUES (1, 'Robin')");
	insertion.execute;
	insertion = db.prepare("INSERT INTO Theboys (id, name) VALUES (2, 'Oscar')");
	insertion.execute;

	insertion.finalize;

	Statement selection = db.prepare("SELECT * FROM Theboys");
	if(selection.execute)
	    for (row in selection)
			print("id: " + row.getInt(0).toS + ", name: " + row.getStr(1));
	else
	    print(selection.errMsg);
}
