use ui;
use core:geometry;
use core:io;

class Dialog extends Frame {
	Label msg;

	init() {
		init("Dialog") {
			msg("Nothing here!");
		}
		size(Size(200, 100));
		msg.pos(Rect(10, 10, 190, 90));
		add(msg);
		create();
	}
}

class DlgMainWin extends Frame {
	private Button button;

	init() {
		init("Main window") {
			button("Show dialog");
		}

		size(Size(200, 200));
		button.pos(Rect(10, 10, 190, 190));
		button.onClick = &this.showDialog();
		add(button);
		create();
	}

	private void showDialog() {
		button.text("Showing dialog...");
		Dialog d;
		d.waitForClose;
		button.text("Show dialog");
	}
}

void dialog() {
	DlgMainWin win;
	win.waitForClose;
}
