use ui;
use core:geometry;

class MenuWindow extends Frame {
	init() {
		MenuBar root;

		init("Menu test", Size(300, 100)) {
			root = root;
		}

		PopupMenu help;
		help << Menu:Text("Help") << Menu:Separator() << Menu:Text("About...", &this.showAbout());

		root << Menu:Text("Test") << Menu:Submenu("Help", help);

		create();
	}

	MenuBar root;

	Bool onClick(Bool pressed, Point at, MouseButton button) : override {
		if (pressed) {
			if (button == MouseButton:left) {
				if (menu)
					menu = null;
				else
					menu = root;
			} else if (button == MouseButton:right) {
				fullscreen = !fullscreen;
			}
		}

		true;
	}

	void showAbout() {
		AboutWindow win;
		Int r = win.show(this);
		print("Result: ${r}");
	}
}

class AboutWindow extends ui:Dialog {
	Button close;

	init() {
		init("About", Size(100, 100)) {
			close("Close");
		}

		close.pos = Rect(10, 10, 80, 80);
		var me = this;
		close.onClick = (Button b) => me.close(1);
		add(close);
	}
}

void menu() {
	FileTypes t("Test files");
	t.add("Text files", ["*.txt"]);
	t.add("Sound files", ["*.mp3", "*.flac"]);

	if (r = showSaveDialog(t, null, "test"))
		print("Opened ${r}");
	return;


	MenuWindow w;
	w.waitForClose;
	print("Done!");
}
