use graphics;
use ui;

/**
 * Presentation.
 */
class Presentation on Render {
	// Title.
	Str title;

	// Slides.
	Slide[] slides;

	// Background color. (replace with brush?)
	Color bg;

	// Background image (if any).
	Image? bgImage;

	// Foreground color.
	Color text;

	// Create.
	ctor(Str title) {
		init() {
			title = title;
			bg = white;
			text = black;
		}
	}

	// Add a slide.
	void add(Slide slide) {
		slides << slide;
	}

}
