use lang.bs;

delimiter = SDelimiter;

SExpr => PExpr(pos, block, title) : "presentation", SString title, "{", (SSlide(block, me) -> add, ";", )* "}";

// A single slide:
SlideExpr SSlide(lang.bs.Block block, PExpr p);
SSlide => SlideExpr(p, type, params, t) :
    SIntro(block) t, SName type, SSlideParams(block) params, "{", (SItem(block) -> add, ";", )* "}";
SSlide => SlideExpr(p, type, params, t) :
    SIntro(block) t, SName type, SSlideParams(block) params;

// Slide intro:
IntroExpr SIntro(lang.bs.Block b);
SIntro => IntroExpr(type, params) : SName type, SSlideParams(b) params, "->";
SIntro => IntroExpr() : "";

// Parameters to a slide.
Actuals SSlideParams(lang.bs.Block b);
SSlideParams => Actuals() : "";
SSlideParams => Actuals() : SExpr(b) -> add (, ",", SExpr(b) -> add)*;

// Items inside a slide.
ItemInfo SItem(Block block);
SItem => itemExpr(block, name, params) : SName name, SSlideParams(block) params;
SItem => itemClickExpr(block, name, params) : "\+", SName name, SSlideParams(block) params;
SItem => itemTimeExpr(block, time, name, params) : "\+", SAtom(block) time, ":", SName name, SSlideParams(block) params;
