use core:io;
use core:geometry;
use graphics;
use ui;

/**
 * Utility functions for testing the implementation. Should be removed in the future.
 */
void basicTest() {
	File pdf;

	Page p(pdf, Rect(0, 0, 500, 800));
	pdf.root.pages << p;

	p.content.data << "175 720 m 175 500 l 300 800 400 600 v 100 650 50 75 re h S";

	Url url = cwdUrl / ".." / "test.pdf";
	print("Writing to ${url}...");
	OStream s = url.write;
	pdf.write(s);
	s.close();
	print("Done!");
}

void draw(Graphics g, Size size) on Render {
	SolidBrush blackBrush(black);
	SolidBrush redBrush(red);
	SolidBrush greenBrush(green);

	SolidBrush transparentBlackBrush(black);
	transparentBlackBrush.opacity = 0.8;

	Path path;
	path.start(Point(100, 100));
	path.bezier(Point(100, 50), Point(50, 100), Point(50, 50));
	path.close();

	path.start(Point(50, 100));
	path.bezier(Point(100, 100), Point(100, 150));

	g.draw(path, redBrush);

	g.line(Point(10, 10), Point(40, 40), blackBrush);
	g.draw(Rect(Point(10, 10), a4 - Size(20)), blackBrush);

	g.fill(Rect(Point(130, 30), Point(150, 40)), redBrush);
	Path p2;
	p2.start(Point(50, 200));
	p2.bezier(Point(70, 200), Point(70, 260), Point(50, 260));
	g.fill(p2, blackBrush);

	g.draw(Rect(Point(130, 100), Size(50, 50)), Size(10), blackBrush);
	g.oval(Rect(Point(140, 170), Size(30, 30)), redBrush);
	g.fill(Rect(Point(130, 160), Size(50, 50)), Size(10), transparentBlackBrush);

	g.oval(Rect(Point(130, 230), Size(40, 40)), blackBrush);
	g.fillOval(Rect(Point(70, 230), Size(40, 40)), redBrush);


	Font f("Arial", 20);
	Rect tRect(30, 140, 100, 140 + f.pxHeight);
	g.fill(tRect, blackBrush);
	g.text("Hello!", f, redBrush, tRect);

	tRect += Point(0, f.pxHeight);
	g.text("ÅÄÖ", f, blackBrush, tRect);

	Text t("Test Format!", f);
	t.layoutBorder = Size(50, 50);
	g.draw(t, blackBrush, Point(130, 40));

	// Clipping.
	g.push();
	g.transform = translate(Point(65, 25)) * rotate(30 deg, Point(15, 15));

	g.push(Rect(Point(), Size(30, 30)));
	g.fill(redBrush);
	g.fillOval(Rect(Point(-2, -2), Point(32, 32)), greenBrush);
	g.pop();

	g.pop();

	// Transparent overlays.
	g.push(0.5);
	g.transform = translate(Point(120, 50));

	g.fill(Rect(0, 0, 30, 30), greenBrush);
	g.fill(Rect(15, 0, 30, 30), redBrush);

	g.pop();
}

class Preview extends Frame {
	init(Size sz, Float scale) {
		init("Preview", sz*scale);

		painter = PreviewPainter(scale);

		create();
	}
}

class PreviewPainter extends Painter {
	Float scale;

	init(Float scale) {
		init() { scale = scale; }
	}

	void render(Size sz, Graphics g) {
		g.transform(scale(scale));
		draw(g, sz);
	}
}

void test() {
	Font f("Arial", 20);
	save();

	// Preview p(a4, 3);
	// p.waitForClose;
}

void save() on Render {
	PdfGraphics g(a4, a4);

	draw(g, a4);

	g.nextPage();
	g.line(Point(0, 0), Point(a4), SolidBrush(black));

	Url url = cwdUrl / ".." / "test.pdf";
	print("Writing to ${url}...");
	g.save(url);
	print("Done!");
}
