* General [7/15]
  - [ ] Graphics::fill does not behave correctly with regards to gradient's coordinate systems.
  - [ ] Swap the two last parameters of Graphics.draw(Text, Brush, Point) to match the others.
  - [ ] TODO: There are cases in which the dialog management deadlocks on Windows. For example:
        main GUI thread waits for a semaphore, and another thread calling waitForClose on a dialog.
  - [ ] See if we should stop rendering a painter that is not visible, eg. inside a scrollwindow.
  - [ ] Make the text view and the multiline text view separate, as we want
        to handle text separatly in the two cases.
  - [ ] 'waitForClose' when called on a frame that has not been shown blocks forever. This is not ideal.
  - [ ] Consider dropping the Cairo GL backend. Then we don't have to ship our own compiled version of
        Cairo, which could cause version incompatibility issues in theory.
  - [ ] Ensure that typefaces are freed properly when using the Skia backend. It seems like the SkTypeface
        is never unreffed, at least in short programs. Likely, this is due to Skia caching the typeface
        somewhere (perhaps next to its texture atlas) for a long time.
  - [X] Apply underline and strikeOut properties on Gtk when a font contains those.
  - [X] There is a chance that copying the rendered cairo surface on Wayland is done in software.
  - [X] Investigate why GTK_MT_HW_COPY experiences fairly large (around 500 ms) stutters from time to time.
        This could be due to our handling of double buffers, but also due to Gtk+ not liking that we're bypassing it.
  - [X] Add a way to create proper modal dialogs with return codes.
  - [X] Window should probably update 'myPos' whenever a window is resized.
  - [X] Investigate why OpenGL rendering fails when maximizing a window containing GL rendering over X forwarding to Windows.
  - [X] Figure out a way to unify the onKey and onChar messages. They are different on Win32 and the same on GTK.
