use test;
use parser;

parseList : parser(List, recursive descent) {
	// Additional packages to import syntax from.
}

suite SimpleRecursive {
	var r = parseList("A, B, C");
	if (x = r.value) {
		print("Got result: ${x}");
	} else {
		print("Error at ${r.end}, ${r.error}");
	}

	// TODO: Test with true/false in them, so we can skip "== true".
	test r.value.any == true;

	Str x = ",A, B, C";
	r = parseList(x, x.begin + 1);
	if (x = r.value) {
		print("Result: ${x}");
	} else {
		print("Error at ${r.end}, ${r.error}");
	}

	test r.value.any == true;
}
