use test;
use parser;

Str check(Result<Int> r) {
	if (x = r.value) {
		x.toS;
	} else {
		"Error at ${r.end}, ${r.error}";
	}
}

inlineParser : parser(recursive descent) {
	start = Start;
	delimiter = Delim;

	Int Start();
	Start => +(a, b) : Num a, "\+", Num b;

	Int Num();
	Num => toInt(x) : "[0-9]+" x;

	void Delim();
	Delim : "[ \n\r\t]*";
}

suite InlineGrammar {
	test check(inlineParser("1 + 3")) == "4";
}
