optional delimiter = OSep;
required delimiter = RSep;

void OSep();
OSep : "[ \n\r\t]*";

void RSep();
RSep : "[ \n\r\t]+";


// Simple list to test LR parser.
Array<Str> List();
List => Array<Str>() : Item -> push, ListTail(me);

void ListTail(Array<Str> x);
ListTail : ;
ListTail => x : ",", Item -> push, ListTail(x);

Str Item();
Item => v : "[A-Z]+" v;
