// The main syntax follows:

DELIMITER : "[ \t\n]+" = delimiter();

// Basic types

Name : {"[A-Za-z][^ ]."} name = createName(name);

Package : Name src[] ('.' Name src[])* = createPkg(src);

Type : Package pkg '.' Name name = createTypePkg(pkg, name);
Type : Name name = createType(name);

// Basic syntax

Expr : '{' (Expr expr[])* '}' = createBlock(expr);
Expr : Name n1 '=' Name n2 ';' = createAssignment(n1, n2);

