use lang.bs;
use core.lang;

optional delimiter = SDelimiter;
required delimiter = SRequiredDelimiter;

// Parser!
SFileItem => parserOverloads(parser) : SParser(env) parser;

// Ways to create a parser.
Parser SParser(Scope env);
SParser => parser
  : SName name #fnName, ":", "parser" #keyword, "(", SType start, ",", SParserType(env, name, start) parser, ")", ";";
SParser => parser
  : SName name #fnName, ":", "parser" #keyword, "(", SType start, ",", SParserType(env, name, start) parser, ")", "{" [, (SParserInclude -> include,)* ]+ "}";

// Includes for a parser.
SrcName SParserInclude();
SParserInclude => v : SPackage v, ";";

// Parser type.
Parser SParserType(Scope env, SStr name, SrcName start) #keyword;
SParserType => RecursiveParser(env, name, start) : "recursive" ~ "descent";
SParserType => RecursiveParser(env, name, start) : "recursive";
