use core:debug;
use core:io;
use lang:syntax;

// Type for storing a sentence.
class Statement {
	SStr noun;
	SStr verb;

	ctor(SStr noun, SStr verb) {
		init() {
			noun = noun;
			verb = verb;
		}
	}
}



void testSentence() {
	// Parse this:
	Str s = "do birds fly?";
	print("Parse: " # s);

	Parser<Sentence> parser;
	print("Created parser: " # parser);
	parser.parse(s, Url());
}

void testEmpty() {
	Str s = "()";
	Parser<SParen> parser;
	parser.parse(s, Url());
}
