use core:unsafe;
use lang:bs:macro;

Variant createStrVariant() {
	Variant("test");
}

Variant createIntVariant() {
	Variant(15);
}

Bool variantRawObj() {
	Variant v("test");
	RawPtr raw(v);

	if (raw.type is named{core:Str}) {
		if (s = raw.asObject() as Str) {
			s == "test";
		} else {
			false;
		}
	} else {
		false;
	}
}

Bool variantRawInt() {
	Variant v(10);
	RawPtr raw(v);

	if (raw.type is named{core:Int}) {
		raw.readInt(0) == 10;
	} else {
		false;
	}
}

Variant variantFromRaw() {
	RawPtr raw = RawPtr:allocArray(named{core:Int}, 1);
	raw.writeFilled(1);
	raw.writeInt(0, 55);

	raw.asVariant();
}

Int saveVariant() {
	RawPtr raw = RawPtr:allocArray(named{core:Int}, 1);
	Variant v(10);
	raw.copyVariant(v);
	raw.readInt(0);
}
