use presentation;
use layout;

// Declare the presentation. Uses an extension implemented in the package 'presentation'.
presentation Simple "My presentation" {
	// Generate a random caption for the first slide.
	Str caption = "Presentation number " + rand(1, 10).toS;

	// Create a slide.
	slide title caption, "By myself" {}

	// Another one, with an animation!
	slide FadeIn => content "Hello!" {
		list [ "Welcome to " + title, "In Storm!" ] {}
	}
}

void main() {
	Simple.show();
}
