use presentation;
use ui;
use core:geometry;
use graphics;
use layout;

presentation Test "Test presentation" {
	Font font("Arial", 32);

	this.background = SolidElement(blue);

	slide {
		Text {}
	}
}


// Main entry-point for testing.
void test() {
	doTest();
}

void doTest() on Render {
	Presentation p("Test presentation");

	p.background = SolidElement(RadialGradient(blue, white, Point(p.size / 2), 500));

	Font font("Arial", 32);

	Slide s;
	s.elements << {
		TextElement e("Hello!", font, black);
		e.pos = Rect(Size(1024, 768));
		e;
	};

	p.slides << s;

	p.show();
}
