// Testing non-context-free grammar in the syntax language.

delimiter = Delim;

void Delim();
Delim : "[ \n\r\t]+";

void Block();
Block : "{", (Stmt,)* "}";

void Stmt();
Stmt : "a";
Stmt : "b";
Stmt : Block;


// Syntax extension: add a new block where 'c' may appear!
Stmt : ExtraC;

void ExtraC();
ExtraC : "extra c", Block = ExtraCProd;
ExtraC..Stmt : "c";


// We can also use an additional production.
Stmt : ExtraD;

void ExtraD();
ExtraD : "extra d", Block;
ExtraD..Stmt : "d";
