* Loose ends so far [3/9]
  - [ ] Destructors in maps and arrays are not working properly yet. Idea: add (yet another) member 
        to array headers, and let the user provide a custom destructor in there if neccessary.
  - [ ] Check so that destructors are required if a value-type object within a class or actor
        contains a destructor.
  - [ ] Improve the preprocessor by automatically adding copy constructors and assignment operators
        where neccessary.
  - [ ] Improve the preprocessor by generating toS() and deepCopy() if not present.
  - [ ] Finish the clone() functionality.
  - [ ] Make sure Array<>, Map<> and Set<> clear the memory when an element is removed.
  - [X] It seems we fail to handle moving objects in Set and Map in rare cases. Examine why!
  - [X] Implement shrink() for Map<> as well.
  - [X] Handles and templates does not work with built-in types (like Int).

* Improvements [0/6]
  - [ ] Clone objects using a member function generated by the STORM_CLASS macro or the preprocessor.
  - [ ] Generate toS() and deepCopy() automatically using the preprocessor unless supressed.
  - [ ] Implement attaching and detaching threads using ThreadGroups for os::Thread.
  - [ ] We can remove a lot of copy-constructors in Code/, and use memcpy + default generated ones!
  - [ ] Remove mov eax, eax (or similar) They are occasionally generated if we're unlucky.
  - [ ] Idea: disallow cloning of values without deepCopy() so that we can safely make iterators for actors.
