// Really simple syntax, mainly for testing the parser.

DELIMITER => void : " *";

// Root rule.
Root => root() : SExpr e;
Root => root() : SExpr, Root;

// Expression
SExpr => sOperator(lhs, rhs, op) : SExpr lhs, "\+" op, SExpr rhs;
SExpr => sOperator(lhs, rhs, op) : SExpr lhs, "-" op, SExpr rhs;
SExpr => sVar() : "[a-z]+" v;
SExpr => sNr() : "[0-9]+" v;

// Root rule with repetitions.
Rep1Root => SScope() : "{", (SExpr -> expr - ";",)+ - "}";
Rep2Root => SScope() : "{", (SExpr -> expr - ";",)* - "}";
Rep3Root => SScope() : "{", (SExpr -> expr - ";",)? - "}";




