#!/bin/bash

echo "Release notes"
echo "===="
echo ""

# Generate release notes from the Git repository.
for c in $(git for-each-ref "refs/tags/release/" --sort=-committerdate --format="%(objectname)")
do
    if [[ $(git cat-file -t $c) == "tag" ]]
    then
	git cat-file -p $c | grep "tag " | sed -E 's!tag +release/!!'
	echo "---"
	echo ""
	git cat-file -p $c | tail -n +6
	echo ""
    fi
done
