#!/bin/bash

if [[ $# -ge 1 ]]
then
    version=$1
else
    version=$(find_version)
fi
echo "Compiling $version..."

echo "core.info" > ${STORM_ROOT}/Compiler/COMPILER.version
echo "$version" >> ${STORM_ROOT}/Compiler/COMPILER.version

cd $STORM_ROOT
mm release -ne || { echo "Compilation failed!"; exit 1; }

echo "Done! Running test suite..."
release/Test --all || { echo "Tests failed!"; exit 1; }

