#!/bin/bash

echo "Release notes"
echo "===="
echo ""

git for-each-ref "refs/tags/release/" --sort='-*committerdate' --format="%(objectname) %(tag) %(taggerdate:iso)" | while read hash tag date time timezone
do
    if [[ $(git cat-file -t $hash) == "tag" ]]
    then
	echo "${tag/release\//} ($date)"
	echo "---"
	echo ""
	git cat-file -p $hash | tail -n +6
	echo ""
    fi
done
