#!/bin/bash

# Build-script executed on the server.

version="$1"
prepared="$2"

release-compile "$version" || { echo "Compilation failed."; exit 1 }
release-package "$packaged"
release-test || { echo "The packaged compiler does not seem to be working."; exit 1; }
