#!/bin/bash

# Build-time packages (installed outside the base system)
# Core: git g++
# Crypto: libssl-dev
# Graphics: libpng-dev libjpeg-dev
# Gui: gtk+-3-dev
# Sound: libopenal-dev libmpg123-dev libogg-dev libflac-dev libvorbis-dev


echo "Generating Debian source package..."

# Fetch mymake if it is not present already.
if [ ! -d mymake ]
then
    echo "Mymake was not found. Fetching it..."
    git clone git://fprg.se/mymake.git mymake
fi

# We need libbacktrace at the moment. I can't find a suitable library for that on Debian (also, it
# is quite small, so no great problems in my opinion). We could live without it if this is a problem.
git submodule init Linux/backtrace
git submodule update Linux/backtrace

# We also need the MPS
git submodule init mps
git submodule update mps

# Clean up any build files that may be in the repository (Note: will not remove the mymake/ repo)
git clean -xdf

# Construct x.y.z-debian+w (keeping +w only if it was present from the beginning)
version=$(find_version)
tar_file=${STORM_ROOT}/storm_${version%+*}.orig.tar
echo "core.info" > ${STORM_ROOT}/Compiler/COMPILER.version
echo "$version" | sed -E 's/^([^+]*)(\+?.*)/\1-debian\2/g' >> ${STORM_ROOT}/Compiler/COMPILER.version

# Generate the changelog:
function changelog {
    git for-each-ref "refs/tags/release/" --sort='-*committerdate' --format="%(objectname) %(tag) %(taggerdate)" | while read hash tag dow month day time year timezone
    do
        if [[ $(git cat-file -t $hash) == "tag" ]]
        then
            echo "storm (${tag/release\//}) unstable; urgency=medium"
            echo
            git cat-file -p $hash | tail -n +6 | sed 's/^$/./' | sed 's/^/  /'
            echo
            echo " -- Filip Strömbäck <filip@fprg.se>  $dow, $day $month $year $time $timezone"
            echo
            echo
        fi
    done
}

changelog > ${STORM_ROOT}/Dist/debian/changelog

# Create the source package as a tar file.
# First: All files, but no submodules.
tar -cf $tar_file --exclude="*/.git" -X<(sed -En "s|^[\t ]*path = (.*)$|./\1|p" ${STORM_ROOT}/.gitmodules) .

# We need the libbacktrace library and the MPS
tar -rf $tar_file ./Linux/backtrace
tar -rf $tar_file ./mps

# Add debian-specific things...
pushd ${STORM_ROOT}/Dist/
tar -rf $tar_file ./debian
tar -rf $tar_file --transform="s/debian-makefile/Makefile/" ./debian-makefile
popd

# Need to compress it for dpkg-buildpackage...
gzip $tar_file

echo "Done!"

# Now: Call dpkg-build...

mkdir -p ${STORM_ROOT}/debbuild
cd ${STORM_ROOT}/debbuild
tar xf $tar_file.gz
dpkg-buildpackage -uc -us
