#!/bin/bash

IN="$1"
if [[ "$IN" == *.zip ]]
then
    extract="7z x $IN"
else
    extract="tar xzf $IN"
fi

echo "Making sure the release $(basename "$IN") works..."
mkdir -p $STORM_ROOT/release/storm
cd $STORM_ROOT/release/storm

$extract > /dev/null
echo "exit" | ./Storm > /dev/null
if [[ $? -ne 0 ]]
then
    echo "Failed to launch the repl. Something is bad! Test in release/storm"
    exit 1
fi

./Storm -c 'tests:bf:inlineBf' > output.txt
if [[ $? -ne 0 ]]
then
    echo "Failed to execute BS code. Test in release/storm"
    exit 1
fi

grep "1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89" output.txt > /dev/null
if [[ $? -ne 0 ]]
then
    echo "Failed to execute BS code. Test in release/storm"
    exit 1
fi

cd $STORM_ROOT
rm -r $STORM_ROOT/release/storm
