// Really simple syntax, mainly for testing the parser.

DELIMITER : " *" = delim();
DELIMITER => " ";

// Root rule.
Root : Expr e[] = root();
Root : Expr, Root = root();

// Expression
Expr : Expr e[], "\+" op, Expr e[] = add();
Expr : Expr e[], "-" op, Expr e[] = sub();
Expr : "a" = var();
Expr : "b" = var();
Expr : "1" = nr();
Expr : "2" = nr();

// Root rule with repetitions.
Rep1Root : "{", (Expr e[] - ";",)+ - "}" = foo();
Rep2Root : "{", (Expr e[] - ";",)* - "}" = foo();
Rep3Root : "{", (Expr e[] - ";",)? - "}" = foo();




