// Really simple syntax, mainly for testing the parser.

DELIMITER : " " = delim();
DELIMITER => " ";

// Root rule.
Root : Expr = root();
Root : Expr, Root = root();

// Expression
Expr : Expr, "\+", Expr = add();
Expr : Expr, "-", Expr = sub();
Expr : "a" = var();
Expr : "b" = var();
Expr : "1" = nr();



