use core:net;
use core:io;
use ssl;

void main() {
	server();
	// client();
}

void server() {
	Certificate c = Certificate:loadPEM(cwdUrl / ".." / "cert.pem");
	print(c.toS);

	ServerContext s;
}

void client() {
	ClientContext context;
	var stream = connect("storm-lang.org", 443);
	if (stream) {
		var session = context.connect(stream, "storm-lang.org");
		print("Got a session!");

		var in = Utf8Input(session.input);
		var out = Utf8Output(session.output, windowsTextInfo());
		out.autoFlush = false;


		out.write("GET / HTTP/1.0\n"); // To disable "chunked"...
		out.write("Host: storm-lang.org\n");
		out.write("\n\n");
		out.flush();

		print(in.readAll());

		session.close();
		print("Done!");
	} else {
		print("Failed to connect.");
	}
}
