
class Abstract {
	Int fun() : abstract;
}

class NoAbstract extends Abstract {
	Int fun() {
		10;
	}
}

Int createAbstract() {
	Abstract x;
	x.fun();
}

Int createNoAbstract() {
	NoAbstract x;
	x.fun();
}



class CppNoAbstract extends debug:DbgAbstract {
	Int member() {
		10;
	}

	Int real() {
		50;
	}
}

Int createCppAbstract() {
	debug:DbgAbstract x;
	x.member();
}

Int createCppNoAbstract() {
	CppNoAbstract x;
	x.member() + x.real();
}
