use core;
use core:debug;

Int testArray() {
	Array<Dbg> a;

	for (Int i = 0; i < 22; i++) {
		a << Dbg(i);
	}

	a[1] = Dbg(0);

	Int sum = 0;
	for (Nat i = 0; i < a.count; i++) {
		sum = sum + a[i].get;
	}

	sum;
}

Int testValArray() {
	Array<DbgVal> a;

	for (Int i = 0; i < 23; i++) {
		a << DbgVal(i);
	}

	a[3] = DbgVal(0);

	Int sum = 0;
	for (Nat i = 0; i < a.count; i++) {
		sum = sum + a[i].get;
	}

	sum;
}

Int testIntArray() {
	Int[] a;

	for (Int i = 0; i < 20; i++)
		a << i;

	for (Int i = 5; i < 15; i++)
		a[i.nat] = 0;

	Int sum;
	for (Nat i = 0; i < a.count; i++)
		sum = sum + a[i];

	sum;
}

Int testInitArray() {
	Int[] a = Int:[1, 3, 3, 7];

	Int sum;
	for (Nat i = 0; i < a.count; i++)
		sum = sum * 10 + a[i];

	sum;

	// Comments with brackets in them causes problems?
	// for foo () {
	// }
	// Hope not!
}

Int testInitAutoArray() {
	var a = [1, 2, 3, 4];

	Int sum;
	for (Nat i = 0; i < a.count; i++)
		sum = sum * 10 + a[i];

	sum;
}

Int testAutoArray() {
	Int[] a = [];
	a.count.int;
}

Int testCastArray() {
	Dbg a(10);
	Dbg b(20);
	Object[] z = [a, b];
	z.count.int;
}

Array<DbgVal> createValArray() {
	Array<DbgVal> a;

	for (Int i = 0; i < 20; i++)
		a << DbgVal(i);

	a;
}

Array<DbgActor> createActorArray() {
	Array<DbgActor> dbg;
	for (Int i = 0; i < 4; i++)
		dbg << DbgActor(i + 1);

	dbg;
}

