use core:debug;

Int byteFn(Byte v) {
	if (v == 1)
		10;
	else
		0;
}

Int natFn(Nat v) {
	if (v == 2)
		10;
	else
		0;
}

Int castToNat() {
	Nat a = 10;
	Byte b = 20;
	byteFn(1) + natFn(2);
}

Int maybeFn(Dbg? t) {
	if (t)
		20;
	else
		10;
}

Int castToMaybe() {
	Dbg v(10);
	maybeFn(v);
}

Int downcastMaybe() {
	DerivedDbg? z = DerivedDbg(10);
	maybeFn(z);
}

void ifCast() {
	DerivedDbg? root;
	Dbg? result = if (1 == 3) {
		root;
	} else {
		Dbg(20);
	};
}

value AutoCast {
	Int v;

	cast ctor(Int v) {
		init() { v = v; }
	}

	cast ctor(Dbg d) {
		init() { v = d.get; }
	}
}

Int autoCast(Int v) {
	Dbg dbg(v);
	AutoCast a = v;
	AutoCast b = dbg;

	a.v + b.v;
}
