use core;
use core:debug;

// Test some object cloning!

value CloneVal {
	Dbg z;

	ctor() {
		super() {
			z = 8;
		}
	}
}

// Base class for cloning.
class CloneBase {
	Int a;
	Dbg b;
	CloneVal v;

	ctor() {
		super() {
			a = 2;
			b = 3;
		}
	}

}

CloneBase createBase() {
	CloneBase a;
	a;
}

Int testClone() {
	CloneBase a;
	CloneBase c = clone(a);
	if (disjoint(a, c)) {
		1;
	} else {
		0;
	}
}
