
// We expect these statements to be executed in the order they appear here.
class InitOrder {
	Int a;
	Int b;
	Int c;

	init() {
		Int ctr = 1;
		init {
			c = ctr++;
			b = ctr++;
			a = ctr++;
		}
	}

	init(Int ctr) {
		init {
			a = ctr++;
			b = ctr++;
			c = ctr++;
		}
	}
}

Int checkInitOrder() {
	InitOrder z;
	z.a * 100 + z.b * 10 + z.c;
}

Int checkInitOrder2() {
	InitOrder z(1);
	z.a * 100 + z.b * 10 + z.c;
}
