// Syntax for debugging...
use lang.bs;

delimiter = SDelimiter;

SStmt => dumpExpr(e, str) : "dump:", ( SExpr(block) e ) str, ";";

// Weak parens.
SAtom => z : "#(", SExpr(block) z, ")#";

// Operators with different associativity
SOperator => lang.bs.rOperator(op, 900) : "#" - "\*"@ op;
SOperator => lang.bs.rOperator(op, 800) : "#" - "\+"@ op;
SOperator => lang.bs.rOperator(op, 800) : "#" - "\-"@ op;
