// Syntax for debugging...
Stmt => dumpExpr(e, str) : "dump:", ( Expr(block) e ) str, ";";

// Weak parens.
Atom => z : "#(", Expr(block) z, ")#";

// Operators with different associativity
Operator => lang.bs.rOperator(op, 900) : "#" - "\*" op;
Operator => lang.bs.rOperator(op, 800) : "#" - "\+" op;
Operator => lang.bs.rOperator(op, 800) : "#" - "\-" op;
