use core;
use core:debug;

class Base {
	Int a;

	Int overload() {
		a;
	}
}

class Derived extends Base {
	Int b;

	Int overload() {
		b;
	}
}

Int extract(Base b) {
	b.overload;
}

Int testBase() {
	Base b = Base();
	// printVTable(b);
	b.a = 10;
	extract(b);
}

Int testDerived() {
	Derived d = Derived();
	// printVTable(d);
	d.a = 10;
	d.b = 20;
	extract(d);
}

class DerivedDbg extends Dbg {
	Int b;

	Int get() {
		b;
	}
}

Int extract(Dbg b) {
	b.get;
}

DerivedDbg derived() {
	DerivedDbg d = DerivedDbg();
	d.b = 20;
	d;
}

Dbg createCpp(Int type) {
	if (type == 1) {
		Dbg();
	} else {
		derived();
	}
}

Int testCpp(Int type) {
	Dbg b = createCpp(type);
	extract(b);
}

