use core:debug;
use lang:bs:macro;

Dbg? maybe(Int v) {
	Dbg? result;
	if (v == 1) {
		result = Dbg(v);
	} else if (v == 2) {
		DerivedDbg z;
		z.set(2);
		z.b = 2;
		result = z;
	}
	result;
}

Int testMaybe(Int v) {
	Dbg? r = maybe(v);
	Int z = 0;

	if (r as DerivedDbg) {
		z = z + r.b;
	}

	if (r) {
		z = z + r.get;
	}

	if (q = r) {
		z = z + q.get;
	}

	z;
}

Int assignMaybe() {
	Dbg? r = Dbg(20);

	if (r)
		1;
	else
		0;
}

Str maybeToS(Int p) {
	Str? r;

	if (p == 1)
		r = "ok";

	r.toS;
}

Int maybeInheritance() {
	DerivedDbg? foo = DerivedDbg(10);
	Dbg? bar = foo;
	// Check assignment as well.
	bar = foo;

	if (bar) {
		bar.get;
	} else {
		0;
	}
}

Int testMaybeInv(Int v) {
	Dbg? r = maybe(v);

	unless (r)
		return 10;

	r.get;
}

Int testMaybeInv2(Int v) {
	Dbg? r = maybe(v);

	unless (w = r)
		return 10;

	w.get;
}
