
class StaticTest {
	Int x;

	init(Int x) {
		init() { x = x; }
	}

	StaticTest create() : static, pure {
		StaticTest(52);
	}

	Int fn(StaticTest z) : static {
		z.x;
	}
}

class StaticDerived extends StaticTest {
	init(Int x) {
		init(x) {}
	}

	Int fn(StaticDerived z) : static {
		z.x + 5;
	}
}

// Check decorators for free functions as well.
Int unity(Int v) : pure {
	v;
}

Int testStatic() {
	StaticTest v = StaticTest:create();
	unity(v.x);
}

Int testStaticInheritance(Int x) {
	StaticTest s = if (x == 0) { StaticTest(10); } else { StaticDerived(10); };

	s.fn();
}
