use core:debug;

Str strConcatTest() {
	"a" # "b" # 1 # "c" # core:lang:Value();
}

Str strConcatError() {
	DbgNoToS z;
	"a" # z # "b";
}

Str strInterpolate() {
	Int a = 20;
	Int b = 30;
	Nat c = 40;
	"|${b}|${a,5}|${a,5l}|${a,5r}|${b,5f+}|${c,x}|";
}

Str strInterpolateFloat() {
	Float a = 2.3456;
	Float b = 1000.2;
	"|${a,d2}|${b,d2}|${a,.2}|${b,.2}|${a,s2}|${b,s2}|${a}|${b}|";
}

value NoToS {
	Int v;
}

// Test the default toS function.
Str defaultToS() {
	NoToS q;
	q.toS;
}

// Iterate through a string, count what is in it.
Int iterateStr(Str v) {
	Int count = 0;
	for (x in v) {
		count++;
	}
	count;
}

Int verifyStr(Str v, Char[] ref) {
	Nat count = 0;

	for (x in v) {
		if (count < ref.count) {
			if (x != ref[count])
				return 0;
		} else {
			return 0;
		}
		count++;
	}

	if (count == ref.count) {
		1;
	} else {
		0;
	}
}
