use core;

class Foo {
Int a = 10;
create() {
"aa\"bb";
'"';
}
}

Int foo(Int p) {
    p - 2;
}

Int bar() {
    var z = 1; var v = 2 * 2;
    foo(z + v);
}

Int ifTest(Int v) {
    if (v == 1) {
       3;
    } else if (v == 2) {
       4;
    } else {
       5;
    }
}

Int ifTest2(Int v) {
    if ((Int z = v + 1) > 1) {
       z;
    } else {
       v - 1;
    }
}

Int assign(Int v) {
    Int z = v;
    if (z == 1) {
       z = 2;
    }
    z;
}

Int while(Int z) {
    Int r = 1;
    while (z > 0) {
        r = r * 2;
	z = z - 1;
    }
    r;
}

Int for(Int z) {
    Int r = 1;
    for (Int i = 0; i < z; i = i + 1) {
        r = r * 2;
    }
    r;
}

Int demo() {
    3;
}
