use core;

class Foo {
    Int a;
    Int b;

    Int foo() {
		a - b;
    }

    void set() {
		a = 10;
		b = 7;
    }
}

Int createFoo() {
	Foo z;
    Foo v = Foo();
    v.set;
	z = v;
	z.foo;
}

Int foo(Int p) {
    p - 2;
}

Int bar() {
    var z = 1; var v = 2 * 2;
    foo(z + v);
}

Int ifTest(Int v) {
    // Let's assume comments work!
    if (v == 1) {
       3;
    } else if (v == 2) {
       4;
    } else {
       5;
    }
}

Int ifTest2(Int v) {
    if ((Int z = v + 1) > 1) {
       z;
    } else {
       v - 1;
    }
}

Int assign(Int v) {
    Int z = v;
    if (z == 1) {
       z = 2;
    }
    z;
}

Int while(Int z) {
    Int r = 1;
    while (z > 0) {
        r = r * 2;
	z = z - 1;
    }
    r;
}

Int for(Int z) {
    Int r = 1;
    for (Int i = 0; i < z; i = i + 1) {
        r = r * 2;
    }
    r;
}

void voidFn() {
    // Make sure we can return 'void'.
    3;
}

void assignError() {
    // Should not compile.
    1 + 1 = 3;
}

Int demo() {
    3;
}
