use ui;
use layout;
use core:geometry;

use lang:bs:macro;

window MyWin {
	// Layout of this window. Actually executed in the scope of 'init', so it is possible to access
	// variables from there.
	layout Grid {
		wrapCols: 2;
		expandCol: 0;
		Button a("A") {}
		Button b("B") { rowspan: 2; }
		Button c("C") {}
		nextLine;
		Button d("D") {}
		Button e("E") {}
		Button f("F") { row: 3; col: 2; }
		Button g("G") { row: 4; col: 1; colspan: 2; }
	}

	init() {
		init("My window", Size(200, 200));

		create();
	}
}


void main() {
	MyWin w;
	w.waitForClose;
}
