use ui;
use ui:layout;
use core:geometry;

class MyWin extends Frame {
	private UiRoot layout;
	private Button[] buttons;

	init() {
		init("My window", Size(400, 400));

		Grid grid;
		grid.wrapCols(2);
		grid.expandRow(0, 1);
		grid.expandRow(1, 2);

		for (x in ["A", "B", "C", "D"]) {
			Button b(x);
			add(b);
			grid.add(component(b));
		}

		layout.add(grid);

		create();
	}

	void resized(Size s) {
		layout.resize(s);
	}
}


void main() {
	MyWin w;
	w.waitForClose;
}
