use ui;
use ui:layout;
use core:geometry;

use lang:bs:macro;

class MyWin extends Frame {
	private UiRoot layout;
	private Button[] buttons;

	init() {
		init("My window", Size(400, 400));

		Button a("A");
		Button b("B");
		Button c("C");
		Button d("D");
		Button e("E");
		Button f("F");
		add(a);
		add(b);
		add(c);
		add(d);
		add(e);
		add(f);

		dump{
			var grid = layout Grid {
				wrapCols: 2;
				expandRow: 0, 1;
				a {}
				b {}
				c {}
				nextLine;
				d {}
				e {}
				f {
					row: 3;
					col: 3;
				}
			}
		};

		// var grid = {
		// 	Grid x;
		// 	x.wrapCols(2);
		// 	x.expandRow(0, 1);
		// 	{
		// 		var z = x.add(component(a));
		// 	}
		// 	{
		// 		var z = x.add(component(b));
		// 	}
		// 	x;
		// };

		// Grid grid;
		// grid.wrapCols(2);
		// grid.expandCol(0, 1);
		// // grid.expandCol(1, 2);

		// for (x in ["A", "B", "C", "D", "E", "F"]) {
		// 	Button b(x);
		// 	add(b);
		// 	grid.add(component(b));
		// }

		layout.add(grid);

		create();
	}

	void resized(Size s) {
		layout.resize(s);
	}
}


void main() {
	MyWin w;
	w.waitForClose;
}
