use ui;
use ui:layout;
use core:geometry;

class MyWin extends Frame {
	private UiRoot layout;
	private Button[] buttons;

	init() {
		init("My window", Size(400, 400));

		// Button a("A");
		// Button b("B");
		// Button c("C");
		// Button d("D");
		// Button e("E");
		// Button f("F");
		// buttons = [a, b, c, d, e, f];

		// Idea for the layout DSL:
		// layout {
		// 	Grid {
		// 	wrapCols: 2;
		// 	expandRow: 0;
		// 		a;
		// 		b;
		// 		c;
		// 	nextLine:
		// 		d;
		// 		e;
		// 		f {
		// 		row: 3;
		// 		col: 3;
		// 		}
		// 	}
		// }

		Grid grid;
		grid.wrapCols(2);
		grid.expandCol(0, 1);
		// grid.expandCol(1, 2);

		for (x in ["A", "B", "C", "D", "E", "F"]) {
			Button b(x);
			add(b);
			grid.add(component(b));
		}

		layout.add(grid);

		create();
	}

	void resized(Size s) {
		layout.resize(s);
	}
}


void main() {
	MyWin w;
	w.waitForClose;
}
