optional delimiter = lang.bs.SDelimiter;
required delimiter = lang.bs.SRequiredDelimiter;

lang.bs.SFreeOption => registerBarrier(item, type) : "cppBarrier", "(", SBarrierType type, ")";

progvis.Barrier SBarrierType() #keyword;
SBarrierType => progvis.Barrier.acquire() : "acquire";
SBarrierType => progvis.Barrier.release() : "release";
SBarrierType => progvis.Barrier.full() : "full";
