use core:lang;

// Create a suitable C++ scope.
Scope cppScope(Package pkg) on Compiler {
	Scope(pkg, CppLookup());
}

/**
 * C++ lookup.
 */
class CppLookup extends ScopeLookup {
	init() {
		init("void") {}
	}

	Named? find(Scope in, SimpleName name) : override {
		NameLookup? at = in.top;
		while (now = at) {
			if (found = find(in, now, name))
				return found;

			at = nextCandidate(now);
		}

		// TODO: Look in the C++ standard path.
		null;
	}
}
